### ISSUE TITLE
Roadmap and plan

### ISSUE THREAD

**Issue by TimothyYe** [go-ignite/ignite#2]
* [x] Support SSR  - Released at 2018.1.12
* [x] Configurable encrypt method  - Released at 2018.1.12
* [x] Support to generate sharing link for SS/SSR - Released at 2018.1.30
* [x] Support to generate QR code picture for SS/SSR - Released at 2018.1.30
